#pragma once

#include <stdio.h>
#include <stdint.h>
#include <stdbool.h>

typedef enum {
	COIL_IR_TRIO_ENABLED,
	COIL_IR_MONO_ENABLED,
	COIL_LOCK_ENABLED,
	COIL_LED_ENABLED,
	COIL_IR_TRIO_STATE,
	COIL_IR_MONO_STATE,
	COIL_IR_LATCHED_STATE,
	COIL_BLINK_LEDS_STATE,
	COIL_LOCK_STATE,
	COIL_OTA_UPDATE_START,
	COIL_OTA_UPDATE_FINISH,
	COIL_OTA_UPDATE_ABORT,
	REGISTER_LOCK_DURATION_STATE,
	REGISTER_CURRENT_VERSION_STATE,
	REGISTER_OTA_UPDATE_DATA_STATE,
	ALL_SETTINGS,
} modbus_function_t;

typedef enum {
	MODBUS_COIL,
	MODBUS_REGISTER,
} modbus_t;